default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>

development:
  <<: *default
  database: "cash_register_development"
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  reconnect: true
  port: 5432

test:
  <<: *default
  database: "cash_register_test"
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  post: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

qa:
  <<: *default

